enum TradeItStoryboardID: String {
    case accountManagementView = "TRADE_IT_ACCOUNT_MANAGEMENT_VIEW"
    case accountSelectionView = "TRADE_IT_ACCOUNT_SELECTION_VIEW"
    case brokerCenterView = "TRADE_IT_BROKER_CENTER_VIEW"
    case brokerManagementView = "TRADE_IT_BROKER_MANAGEMENT_VIEW"
    case loginView = "TRADE_IT_LOGIN_VIEW"
    case oAuthCompletionView = "TRADE_IT_OAUTH_COMPLETION_VIEW"
    case portfolioView = "TRADE_IT_PORTFOLIO_VIEW"
    case selectBrokerView = "TRADE_IT_SELECT_BROKER_VIEW"
    case symbolSearchView = "TRADE_IT_SYMBOL_SEARCH_VIEW"
    case tradingConfirmationView = "TRADE_IT_TRADING_CONFIRMATION_VIEW"
    case tradingPreviewView = "TRADE_IT_TRADING_PREVIEW_VIEW"
    case tradingTicketView = "TRADE_IT_TRADING_TICKET_VIEW"
    case webView = "TRADE_IT_WEB_VIEW"
    case welcomeView = "TRADE_IT_WELCOME_VIEW"
    case navView = "TRADE_IT_NAV_VIEW"
    // Yahoo
    case yahooAccountSelectionView = "TRADE_IT_YAHOO_ACCOUNT_SELECTION_VIEW"
    case yahooBrokerLinkedView = "TRADE_IT_YAHOO_BROKER_LINKED_VIEW"
    case yahooBrokerSelectionView = "TRADE_IT_YAHOO_BROKER_SELECTION_VIEW"
    case yahooSelectionView = "TRADE_IT_YAHOO_SELECTION_VIEW"
    case yahooTradingPreviewView = "TRADE_IT_YAHOO_TRADING_PREVIEW_VIEW"
    case yahooTradingTicketView = "TRADE_IT_YAHOO_TRADING_TICKET_VIEW"
}
